# Generated by Django 4.0.2 on 2022-04-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('distance', models.IntegerField(default=0, verbose_name='Расстояние')),
            ],
        ),
    ]
